services:
  - type: web
    name: justhear-react
    env: static
    buildCommand: npm install && npm run build
    startCommand: npm run start
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
