services:
  - type: web
    name: justhear-frontend
    env: static
    buildCommand: |
      npm ci --prefer-offline --no-audit --no-fund --loglevel=error
      npm run build:fast
    startCommand: npm start
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://justhear-backend.onrender.com
      - key: CI
        value: true
    headers:
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
      - path: /assets/*.js
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /assets/*.css
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - vite.config.ts
        - tailwind.config.js
        - tsconfig.json
        - index.html
      ignorePaths:
        - node_modules/**
        - .git/**
        - dist/**
        - .vscode/**
        - .idea/**
        - *.log
        - .env*
        - README.md
        - DEPLOYMENT_OPTIMIZATION.md
