services:
  - type: web
    name: justhear-frontend
    env: static
    buildCommand: npm ci && npm run build:fast
    startCommand: npm start
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://justhear-backend.onrender.com
    headers:
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html
